/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/convert/{target}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert a file to a named format
         * @description Converts the upload to `target`, which must be an id from
         *     `GET /formats` (`pdf`, `odt`, `docx`, `txt`, `html`, `rtf`, `epub`,
         *     `ods`, `xlsx`, `csv`, `odp`, `pptx`, `png`, `jpg`).
         *
         *     The document is parsed by LibreOffice, which is a large C++ codebase
         *     handling untrusted input. **Treat a conversion failure as an expected,
         *     normal event**, not as an incident.
         *
         *     The endpoint is unauthenticated and cannot be otherwise: the client is
         *     an APK, so any secret shipped inside it is public. Requests are
         *     rate-limited per IP and conversions run under a bounded concurrency
         *     limit; both are sources of `429` and `503` that a well-formed request
         *     can hit.
         */
        post: operations["convertToFormat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The conversion matrix
         * @description Every source extension this service accepts, and every target each one
         *     can become.
         *
         *     Exists so a client does not have to hard-code the table: the shipped
         *     client is an APK, and without this, teaching it a new output format
         *     would mean shipping a new APK. A client that hard-codes the matrix will
         *     silently disagree with the server the first time the server grows.
         */
        get: operations["listFormats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns `ok` once the service is ready to convert.
         *
         *     The service only begins listening after LibreOffice has been confirmed
         *     on `PATH`, the rasteriser has been confirmed, the metric-compatible
         *     fonts have been verified, and a warm-up conversion has succeeded **for
         *     every document family** - so reaching this endpoint at all means the
         *     whole matrix is ready, not merely that the process is up.
         *
         *     It does not exercise a conversion of its own.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Identifier of an output format, as used in the `/convert/{target}` path
         *     and returned by `GET /formats`.
         * @enum {string}
         */
        TargetId: "pdf" | "odt" | "docx" | "txt" | "html" | "rtf" | "epub" | "ods" | "xlsx" | "csv" | "odp" | "pptx" | "png" | "jpg";
        /**
         * @description Stable machine-readable identifier for the failure. For logs, metrics
         *     and support only - the client never shows this to the user.
         * @enum {string}
         */
        ErrorCode: "E_CONVERT_FAILED" | "E_TIMEOUT" | "E_ENCRYPTED" | "E_UNSUPPORTED" | "E_UNSUPPORTED_TARGET" | "E_UNKNOWN_TARGET" | "E_TOO_LARGE" | "E_BUSY" | "E_BAD_REQUEST" | "E_RATE_LIMITED" | "E_INTERNAL";
        /**
         * @description The body of every non-2xx response. There are no exceptions: error
         *     paths that Express or multer would normally render as an HTML page are
         *     overridden to produce this shape.
         */
        ErrorEnvelope: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /**
                 * @description A complete sentence shown verbatim in a dialog on the phone.
                 *     Never a stack trace, a file path or a bare code.
                 */
                message: string;
            };
        };
    };
    responses: {
        /** @description The converted document, as PDF. */
        ConvertedToPdf: {
            headers: {
                /**
                 * @description Identifier for this request, also present in the server log line.
                 *     Quote it when reporting a problem.
                 */
                "X-Request-Id"?: string;
                /** @example attachment; filename="Quarterly report.pdf"; filename*=UTF-8''Quarterly%20report.pdf */
                "Content-Disposition"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/pdf": string;
            };
        };
        /**
         * @description The converted file.
         *
         *     The media type is the target's own - `application/pdf` for `pdf`,
         *     `text/csv` for `csv`, and so on. **The image targets are the exception**:
         *     `png` and `jpg` always answer with `application/zip`, because there is
         *     one image per page and a ZIP is the only way to put several files in one
         *     response.
         */
        ConvertedToTarget: {
            headers: {
                "X-Request-Id"?: string;
                /**
                 * @description The uploaded file's name with the target's extension. Sanitised:
                 *     path segments and control characters are stripped, and a name with
                 *     nothing usable in it becomes `converted.<ext>`.
                 *
                 *     Sent in both RFC 6266 forms - a quoted ASCII `filename` for older
                 *     clients and a percent-encoded UTF-8 `filename*` for current ones -
                 *     so a non-ASCII name survives.
                 * @example attachment; filename="Quarterly report.xlsx"; filename*=UTF-8''Quarterly%20report.xlsx
                 */
                "Content-Disposition"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/pdf": string;
                "application/zip": string;
                "application/vnd.oasis.opendocument.text": string;
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document": string;
                "application/vnd.oasis.opendocument.spreadsheet": string;
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                "application/vnd.oasis.opendocument.presentation": string;
                "application/vnd.openxmlformats-officedocument.presentationml.presentation": string;
                "application/epub+zip": string;
                "application/rtf": string;
                "text/plain": string;
                "text/csv": string;
                "text/html": string;
            };
        };
        /**
         * @description The request was not a usable upload: no file part named `file`, several
         *     files, or a part under a different name.
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_BAD_REQUEST",
                 *         "message": "The document could not be received. Please try again."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description No such endpoint. In practice this means the client is older than the
         *     server, which is why the message tells the user to update the app.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_BAD_REQUEST",
                 *         "message": "The converter is not available at this address. Please update the app and try again."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The target in the path is not a format this service can produce at all -
         *     `/convert/banana`. Distinct from a real target the source cannot become,
         *     which is a `415`: this one is a `404` because the address does not exist.
         */
        UnknownTarget: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_UNKNOWN_TARGET",
                 *         "message": "That is not a format this converter can produce. Available: PDF, ODT, DOCX, TXT, HTML, RTF, EPUB, ODS, XLSX, CSV, ODP, PPTX, PNG, JPG."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The upload exceeds 26214400 bytes (25 MB). Applied by the reverse proxy,
         *     by the multipart parser and by the client, all using the same limit.
         *
         *     Also returned when an image target would produce more pages than the
         *     server will hold in memory at once, which is a bound on the archive
         *     rather than on the upload.
         */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_TOO_LARGE",
                 *         "message": "This document is too large to convert."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The filename extension is not one this service accepts. The extension -
         *     not the declared MIME type - selects the import filter.
         *
         *     The message lists the accepted extensions, because the person holding
         *     the phone has a file they believe is a document, and "unsupported"
         *     alone tells them nothing about what would work.
         */
        Unsupported: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_UNSUPPORTED",
                 *         "message": "This file type cannot be converted. Supported types: .docx, .docm, .doc, .odt, .ods, .odp, .xlsx, .pptx, .csv, .txt, .html, .htm, .rtf, .png, .jpg, .jpeg."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description A real target, but not one this source can become - asking for `png`
         *     from a `.docx`, say. This is a `415` and not a `404`, because the
         *     address exists; it is the combination that does not.
         *
         *     The message names what the document CAN become instead, because the
         *     useful answer to "can I have this as X" is "no, but here is what you can
         *     have". The list varies by source, so the example below is the one for a
         *     Word document; see `GET /formats` for the rest.
         */
        UnsupportedTarget: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_UNSUPPORTED_TARGET",
                 *         "message": "A .docx file can be converted to: PDF, ODT, TXT, HTML, RTF, EPUB."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The document is password protected. Detected before LibreOffice runs,
         *     because LibreOffice reports an encrypted document the same way it
         *     reports a corrupt one, and telling a user their file is damaged when it
         *     merely needs a password is both wrong and unhelpful.
         */
        Encrypted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_ENCRYPTED",
                 *         "message": "This document is password protected."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests from this address in the current window. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_RATE_LIMITED",
                 *         "message": "Too many requests. Try again in a moment."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The conversion produced nothing. Covers a damaged document, a document
         *     whose content does not match its extension, and a zero-byte upload.
         *
         *     Note that LibreOffice's exit code is **not** used to decide this:
         *     `--convert-to` exits `0` even when it converts nothing, so the only
         *     trustworthy signal is whether a non-empty file of the expected type
         *     appeared on disk.
         */
        ConvertFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Every conversion slot is taken and the waiting queue is full. Returned
         *     immediately rather than queueing without bound, so the client gets a
         *     fast, honest answer instead of a request that hangs until it times out.
         */
        Busy: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_BUSY",
                 *         "message": "The converter is busy. Try again in a moment."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description The conversion exceeded the server's 90 second deadline. The running
         *     LibreOffice process is sent `SIGTERM` and then `SIGKILL`.
         *
         *     This is deliberately shorter than the client's own 120 second abort, so
         *     that the server answers with this response rather than being killed
         *     mid-conversion and leaving the phone to report a network failure.
         */
        Timeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "E_TIMEOUT",
                 *         "message": "This document took too long to convert."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: {
        /**
         * @description Exactly one file part named `file`. Additional parts, or a part under
         *     a different name, are rejected with `400`.
         *
         *     The overall body limit is **26214400 bytes (25 MB)**, matching the
         *     client's own `MAX_UPLOAD_BYTES` and the reverse proxy's body limit.
         *     Exceeding it at any layer produces `413`.
         */
        Upload: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to convert. Its **filename extension** selects the
                     *     import filter and must be one of the extensions listed by
                     *     `GET /formats` (case-insensitive). The declared `Content-Type`
                     *     of this part is ignored.
                     *
                     *     The filename is never used as a path on disk: the upload is
                     *     written to a server-generated name inside a per-request
                     *     temporary directory, so a name like `../../etc/passwd.docx`
                     *     is harmless.
                     */
                    file: string;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    convertToFormat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The format to produce. Case-sensitive, without a leading dot. */
                target: components["schemas"]["TargetId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Upload"];
        responses: {
            200: components["responses"]["ConvertedToTarget"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["UnknownTarget"];
            413: components["responses"]["TooLarge"];
            415: components["responses"]["UnsupportedTarget"];
            422: components["responses"]["Encrypted"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ConvertFailed"];
            503: components["responses"]["Busy"];
            504: components["responses"]["Timeout"];
        };
    };
    listFormats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matrix. */
            200: {
                headers: {
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "sources": [
                     *         {
                     *           "extension": ".docx",
                     *           "mediaType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                     *           "family": "writer",
                     *           "targets": [
                     *             "pdf",
                     *             "odt",
                     *             "txt",
                     *             "html",
                     *             "rtf",
                     *             "epub"
                     *           ]
                     *         }
                     *       ],
                     *       "targets": [
                     *         {
                     *           "id": "pdf",
                     *           "extension": ".pdf",
                     *           "mediaType": "application/pdf",
                     *           "label": "PDF",
                     *           "multiple": false
                     *         },
                     *         {
                     *           "id": "png",
                     *           "extension": ".png",
                     *           "mediaType": "image/png",
                     *           "label": "PNG",
                     *           "multiple": true
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /** @description Accepted upload types, keyed by extension. */
                        sources: {
                            /** @example .docx */
                            extension: string;
                            mediaType: string;
                            /**
                             * @description The LibreOffice document family that handles it.
                             *     Sources in the same family convert the same way.
                             * @enum {string}
                             */
                            family: "writer" | "calc" | "impress" | "draw";
                            targets: components["schemas"]["TargetId"][];
                        }[];
                        /** @description Every format this service can produce. */
                        targets: {
                            id: components["schemas"]["TargetId"];
                            /** @example .pdf */
                            extension: string;
                            mediaType: string;
                            /**
                             * @description Short name, as used in error messages.
                             * @example PDF
                             */
                            label: string;
                            /**
                             * @description When true the response is a ZIP of one file per page
                             *     rather than a single file. Always an archive for
                             *     these, even for a one-page source.
                             */
                            multiple: boolean;
                        }[];
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready. */
            200: {
                headers: {
                    "X-Request-Id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
}
