/* GENERATED by scripts/gen-file-matrix.mjs from the backend's formats.ts. Do not edit. */

export const FILE_TARGETS: Readonly<Record<string, { label: string; extension: string }>> = {
  "obj": {
    "label": "OBJ",
    "extension": ".obj"
  },
  "stl": {
    "label": "STL",
    "extension": ".stl"
  },
  "ply": {
    "label": "PLY",
    "extension": ".ply"
  },
  "glb": {
    "label": "GLB",
    "extension": ".glb"
  },
  "zip": {
    "label": "ZIP",
    "extension": ".zip"
  },
  "tar": {
    "label": "TAR",
    "extension": ".tar"
  },
  "tar.gz": {
    "label": "TAR.GZ",
    "extension": ".tar.gz"
  },
  "tar.bz2": {
    "label": "TAR.BZ2",
    "extension": ".tar.bz2"
  },
  "tar.zst": {
    "label": "TAR.ZST",
    "extension": ".tar.zst"
  },
  "cbz": {
    "label": "CBZ",
    "extension": ".cbz"
  },
  "bmp": {
    "label": "BMP",
    "extension": ".bmp"
  },
  "gif": {
    "label": "GIF",
    "extension": ".gif"
  },
  "tiff": {
    "label": "TIFF",
    "extension": ".tiff"
  },
  "webp": {
    "label": "WEBP",
    "extension": ".webp"
  },
  "avif": {
    "label": "AVIF",
    "extension": ".avif"
  },
  "ico": {
    "label": "ICO",
    "extension": ".ico"
  },
  "png-image": {
    "label": "PNG (image)",
    "extension": ".png"
  },
  "jpg-image": {
    "label": "JPG (image)",
    "extension": ".jpg"
  },
  "jxl": {
    "label": "JXL",
    "extension": ".jxl"
  },
  "jp2": {
    "label": "JPEG 2000",
    "extension": ".jp2"
  },
  "qoi": {
    "label": "QOI",
    "extension": ".qoi"
  },
  "tga": {
    "label": "TGA",
    "extension": ".tga"
  },
  "pcx": {
    "label": "PCX",
    "extension": ".pcx"
  },
  "heic": {
    "label": "HEIC",
    "extension": ".heic"
  },
  "heif": {
    "label": "HEIF",
    "extension": ".heif"
  },
  "srt": {
    "label": "SRT",
    "extension": ".srt"
  },
  "vtt": {
    "label": "VTT",
    "extension": ".vtt"
  },
  "ssa": {
    "label": "SSA",
    "extension": ".ssa"
  },
  "apng": {
    "label": "APNG",
    "extension": ".apng"
  },
  "epub": {
    "label": "EPUB",
    "extension": ".epub"
  },
  "mobi": {
    "label": "MOBI",
    "extension": ".mobi"
  },
  "fb2": {
    "label": "FB2",
    "extension": ".fb2"
  },
  "lrf": {
    "label": "LRF",
    "extension": ".lrf"
  },
  "pdb": {
    "label": "PDB",
    "extension": ".pdb"
  },
  "snb": {
    "label": "SNB",
    "extension": ".snb"
  },
  "kepub": {
    "label": "KEPUB",
    "extension": ".kepub.epub"
  },
  "7z": {
    "label": "7Z",
    "extension": ".7z"
  },
  "xlsx": {
    "label": "XLSX",
    "extension": ".xlsx"
  },
  "ods": {
    "label": "ODS",
    "extension": ".ods"
  },
  "pdf": {
    "label": "PDF",
    "extension": ".pdf"
  },
  "html": {
    "label": "HTML",
    "extension": ".html"
  },
  "tsv": {
    "label": "TSV",
    "extension": ".tsv"
  },
  "json": {
    "label": "JSON",
    "extension": ".json"
  },
  "yaml": {
    "label": "YAML",
    "extension": ".yaml"
  },
  "jsonl": {
    "label": "JSONL",
    "extension": ".jsonl"
  },
  "xml": {
    "label": "XML",
    "extension": ".xml"
  },
  "toml": {
    "label": "TOML",
    "extension": ".toml"
  },
  "ini": {
    "label": "INI",
    "extension": ".ini"
  },
  "sqlite": {
    "label": "SQLite",
    "extension": ".sqlite"
  },
  "parquet": {
    "label": "Parquet",
    "extension": ".parquet"
  },
  "orc": {
    "label": "ORC",
    "extension": ".orc"
  },
  "feather": {
    "label": "Feather",
    "extension": ".feather"
  },
  "docx": {
    "label": "DOCX",
    "extension": ".docx"
  },
  "odt": {
    "label": "ODT",
    "extension": ".odt"
  },
  "txt": {
    "label": "TXT",
    "extension": ".txt"
  },
  "rtf": {
    "label": "RTF",
    "extension": ".rtf"
  },
  "tables": {
    "label": "XLSX (tables)",
    "extension": ".xlsx"
  },
  "svg": {
    "label": "SVG",
    "extension": ".svg"
  },
  "wmf": {
    "label": "WMF",
    "extension": ".wmf"
  },
  "eps": {
    "label": "EPS",
    "extension": ".eps"
  },
  "emf": {
    "label": "EMF",
    "extension": ".emf"
  },
  "azw3": {
    "label": "AZW3",
    "extension": ".azw3"
  },
  "csv": {
    "label": "CSV",
    "extension": ".csv"
  },
  "3mf": {
    "label": "3MF",
    "extension": ".3mf"
  },
  "markdown": {
    "label": "Markdown",
    "extension": ".md"
  },
  "pptx": {
    "label": "PPTX",
    "extension": ".pptx"
  },
  "png": {
    "label": "PNG",
    "extension": ".png"
  },
  "jpg": {
    "label": "JPG",
    "extension": ".jpg"
  },
  "ttf": {
    "label": "TTF",
    "extension": ".ttf"
  },
  "woff": {
    "label": "WOFF",
    "extension": ".woff"
  },
  "woff2": {
    "label": "WOFF2",
    "extension": ".woff2"
  },
  "pdfa": {
    "label": "PDF/A",
    "extension": ".pdf"
  },
  "odp": {
    "label": "ODP",
    "extension": ".odp"
  },
  "layers": {
    "label": "PNG (layers)",
    "extension": ".png"
  },
  "ass": {
    "label": "ASS",
    "extension": ".ass"
  },
  "otf": {
    "label": "OTF",
    "extension": ".otf"
  }
};

/** Every source extension the service accepts, and the target ids it reaches. */
export const FILE_MATRIX: Readonly<Record<string, readonly string[]>> = {
  ".3mf": [
    "obj",
    "stl",
    "ply",
    "glb"
  ],
  ".7z": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "cbz"
  ],
  ".apng": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "heic",
    "heif"
  ],
  ".ass": [
    "srt",
    "vtt",
    "ssa"
  ],
  ".avif": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".azw3": [
    "epub",
    "mobi",
    "fb2",
    "lrf",
    "pdb",
    "snb",
    "kepub"
  ],
  ".bmp": [
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".bz2": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".cbz": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z"
  ],
  ".csv": [
    "xlsx",
    "ods",
    "pdf",
    "html",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".doc": [
    "pdf",
    "docx",
    "odt",
    "txt",
    "html",
    "rtf",
    "epub"
  ],
  ".docm": [
    "pdf",
    "docx",
    "odt",
    "txt",
    "html",
    "rtf",
    "epub",
    "tables"
  ],
  ".docx": [
    "pdf",
    "odt",
    "txt",
    "html",
    "rtf",
    "epub",
    "tables"
  ],
  ".dot": [
    "pdf",
    "docx",
    "odt",
    "txt",
    "html",
    "rtf",
    "epub"
  ],
  ".dotx": [
    "pdf",
    "docx",
    "odt",
    "txt",
    "html",
    "rtf",
    "epub"
  ],
  ".emf": [
    "pdf",
    "svg",
    "wmf",
    "eps"
  ],
  ".eml": [
    "txt",
    "html"
  ],
  ".eps": [
    "pdf",
    "svg",
    "emf",
    "wmf"
  ],
  ".epub": [
    "mobi",
    "azw3",
    "fb2",
    "lrf",
    "pdb",
    "snb",
    "kepub"
  ],
  ".fb2": [
    "epub",
    "mobi",
    "azw3",
    "lrf",
    "pdb",
    "snb",
    "kepub"
  ],
  ".feather": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc"
  ],
  ".gif": [
    "bmp",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".glb": [
    "obj",
    "stl",
    "ply",
    "3mf"
  ],
  ".gz": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".heic": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heif"
  ],
  ".heif": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic"
  ],
  ".htm": [
    "pdf",
    "docx",
    "odt",
    "txt",
    "rtf",
    "epub"
  ],
  ".html": [
    "pdf",
    "docx",
    "odt",
    "txt",
    "rtf",
    "epub"
  ],
  ".ico": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".ini": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".ipynb": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".iso": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".jp2": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".jpeg": [
    "pdf",
    "svg",
    "emf",
    "wmf",
    "eps",
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".jpg": [
    "pdf",
    "svg",
    "emf",
    "wmf",
    "eps",
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".json": [
    "csv",
    "tsv",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".jsonl": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".jxl": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".lrf": [
    "epub",
    "mobi",
    "azw3",
    "fb2",
    "pdb",
    "snb",
    "kepub"
  ],
  ".md": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt"
  ],
  ".mobi": [
    "epub",
    "azw3",
    "fb2",
    "lrf",
    "pdb",
    "snb",
    "kepub"
  ],
  ".muse": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".obj": [
    "stl",
    "ply",
    "glb",
    "3mf"
  ],
  ".odg": [
    "pdf"
  ],
  ".odp": [
    "pdf",
    "pptx",
    "png",
    "jpg"
  ],
  ".ods": [
    "pdf",
    "xlsx",
    "html",
    "csv"
  ],
  ".odt": [
    "pdf",
    "docx",
    "txt",
    "html",
    "rtf",
    "epub"
  ],
  ".off": [
    "obj",
    "stl",
    "ply",
    "glb",
    "3mf"
  ],
  ".opml": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".orc": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "feather"
  ],
  ".org": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".otf": [
    "ttf",
    "woff",
    "woff2"
  ],
  ".parquet": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "orc",
    "feather"
  ],
  ".pcx": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "apng",
    "heic",
    "heif"
  ],
  ".pdb": [
    "epub",
    "mobi",
    "azw3",
    "fb2",
    "lrf",
    "snb",
    "kepub"
  ],
  ".pdf": [
    "pdfa",
    "png",
    "jpg",
    "svg",
    "emf",
    "wmf",
    "eps",
    "docx",
    "pptx",
    "xlsx",
    "markdown"
  ],
  ".ply": [
    "obj",
    "stl",
    "glb",
    "3mf"
  ],
  ".png": [
    "pdf",
    "svg",
    "emf",
    "wmf",
    "eps",
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".pot": [
    "pdf",
    "pptx",
    "odp",
    "png",
    "jpg"
  ],
  ".potx": [
    "pdf",
    "pptx",
    "odp",
    "png",
    "jpg"
  ],
  ".pps": [
    "pdf",
    "pptx",
    "odp",
    "png",
    "jpg"
  ],
  ".ppsx": [
    "pdf",
    "pptx",
    "odp",
    "png",
    "jpg"
  ],
  ".ppt": [
    "pdf",
    "pptx",
    "odp",
    "png",
    "jpg"
  ],
  ".pptm": [
    "pdf",
    "pptx",
    "odp",
    "png",
    "jpg"
  ],
  ".pptx": [
    "pdf",
    "odp",
    "png",
    "jpg"
  ],
  ".psd": [
    "layers"
  ],
  ".qoi": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".rar": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".rst": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".rtf": [
    "docx",
    "pdf",
    "odt",
    "txt",
    "html",
    "epub"
  ],
  ".sqlite": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "parquet",
    "orc",
    "feather"
  ],
  ".srt": [
    "vtt",
    "ass",
    "ssa"
  ],
  ".ssa": [
    "srt",
    "vtt",
    "ass"
  ],
  ".stl": [
    "obj",
    "ply",
    "glb",
    "3mf"
  ],
  ".svg": [
    "pdf",
    "emf",
    "wmf",
    "eps",
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".tar": [
    "zip",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".tbz2": [
    "zip",
    "tar",
    "tar.gz",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".tex": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".textile": [
    "docx",
    "html",
    "odt",
    "rtf",
    "txt",
    "markdown"
  ],
  ".tga": [
    "bmp",
    "gif",
    "tiff",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".tgz": [
    "zip",
    "tar",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".tiff": [
    "bmp",
    "gif",
    "webp",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".toml": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".tsv": [
    "csv",
    "json",
    "yaml",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".ttf": [
    "otf",
    "woff",
    "woff2"
  ],
  ".txt": [
    "pdf",
    "docx",
    "odt",
    "html",
    "rtf",
    "epub"
  ],
  ".txz": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".vtt": [
    "srt",
    "ass",
    "ssa"
  ],
  ".webp": [
    "bmp",
    "gif",
    "tiff",
    "avif",
    "ico",
    "png-image",
    "jpg-image",
    "jxl",
    "jp2",
    "qoi",
    "tga",
    "pcx",
    "apng",
    "heic",
    "heif"
  ],
  ".wmf": [
    "pdf",
    "svg",
    "emf",
    "eps"
  ],
  ".woff": [
    "ttf",
    "otf",
    "woff2"
  ],
  ".woff2": [
    "ttf",
    "otf",
    "woff"
  ],
  ".xls": [
    "pdf",
    "xlsx",
    "ods",
    "csv",
    "html"
  ],
  ".xlsm": [
    "pdf",
    "xlsx",
    "ods",
    "csv",
    "html"
  ],
  ".xlsx": [
    "pdf",
    "ods",
    "csv",
    "html"
  ],
  ".xml": [
    "csv",
    "tsv",
    "json",
    "yaml",
    "jsonl",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".xz": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".yaml": [
    "csv",
    "tsv",
    "json",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".yml": [
    "csv",
    "tsv",
    "json",
    "jsonl",
    "xml",
    "toml",
    "ini",
    "sqlite",
    "parquet",
    "orc",
    "feather"
  ],
  ".zip": [
    "tar",
    "tar.gz",
    "tar.bz2",
    "tar.zst",
    "7z",
    "cbz"
  ],
  ".zst": [
    "zip",
    "tar",
    "tar.gz",
    "tar.bz2",
    "7z",
    "cbz"
  ]
};
